default: &default
  adapter: postgresql
  encoding: unicode
  pool: 20
  schema_search_path: public
  port: 5432

development:
  <<: *default
  database: <%= ENV['DEVELOPMENT_DATABASE'] %>
  username: <%= ENV['DEVELOPMENT_DB_USERNAME'] %>
  password: <%= ENV['DEVELOPMENT_DB_PASSWORD'] %>
  host: <%= ENV['DEVELOPMENT_HOST'] %>

test:
  <<: *default
  database: <%= ENV['TEST_DATABASE'] %>
  username: <%= ENV['TEST_DB_USERNAME'] %>
  password: <%= ENV['TEST_DB_PASSWORD'] %>
  host: <%= ENV['TEST_HOST'] %>

production:
  <<: *default
  database: <%= ENV['PRODUCTION_DATABASE'] %>
  username: <%= ENV['PRODUCTION_DB_USERNAME'] %>
  password: <%= ENV['PRODUCTION_DB_PASSWORD'] %>
