# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: de2befe98840e4a9d56152b01dcc334e0b3f512a70ed5c7e066a03d6e0b48d402e978e3f1652326b4096d93c23043e9e00767604339f576bc2b774f3300d168b

test:
  secret_key_base: e7c047c3a90a17fbf23b169c21dc93db36e5427f8b2f299673c9c5a99c69fcd0700431bafbf286b3db84c2a8a4e612928fddc7cdfa3e4555f33f3824a84a5136

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
